import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { featureVector } from '../src/features.js';
import { FEATURE_SPEC_VERSION, PER_CHANNEL_FEATURES, featureNames } from '../src/spec.js';

const RTOL = 1e-5;
const ATOL = 1e-8;

interface GoldenCase {
  name: string;
  samplingRateHz: number;
  channels: number[][];
  featureNames: string[];
  featureVector: number[];
}

interface Golden {
  featureSpecVersion: number;
  perChannelFeatures: string[];
  config: {
    samplingRateHz: number;
    zeroCrossingThreshold: number;
    slopeSignThreshold: number;
  };
  cases: GoldenCase[];
}

const golden: Golden = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('../../../fixtures/conformance/golden.json', import.meta.url)),
    'utf-8',
  ),
);

describe('Python/TypeScript feature conformance', () => {
  it('fixture was generated by the same spec version this build implements', () => {
    expect(golden.featureSpecVersion).toBe(FEATURE_SPEC_VERSION);
    expect(golden.perChannelFeatures).toEqual([...PER_CHANNEL_FEATURES]);
  });

  it('has cases to check', () => {
    expect(golden.cases.length).toBeGreaterThan(0);
  });

  for (const goldenCase of golden.cases) {
    it(`matches Python on "${goldenCase.name}"`, () => {
      const channels = goldenCase.channels.map((row) => Float64Array.from(row));
      const actual = featureVector(channels, {
        samplingRateHz: goldenCase.samplingRateHz,
        zeroCrossingThreshold: golden.config.zeroCrossingThreshold,
        slopeSignThreshold: golden.config.slopeSignThreshold,
      });

      const names = featureNames(channels.length);
      expect(names).toEqual(goldenCase.featureNames);
      expect(actual.length).toBe(goldenCase.featureVector.length);

      // Report the single worst disagreement by name. A bare "arrays differ"
      // would leave the next engineer bisecting seventeen features by hand.
      let worstName = '';
      let worstError = 0;
      let worstExpected = 0;
      let worstActual = 0;

      for (let i = 0; i < actual.length; i++) {
        const expectedValue = goldenCase.featureVector[i]!;
        const actualValue = actual[i]!;
        const tolerance = ATOL + RTOL * Math.abs(expectedValue);
        const error = Math.abs(actualValue - expectedValue) - tolerance;
        if (error > worstError) {
          worstError = error;
          worstName = names[i]!;
          worstExpected = expectedValue;
          worstActual = actualValue;
        }
      }

      expect(
        worstError,
        worstError > 0
          ? `${worstName}: python=${worstExpected} typescript=${worstActual}`
          : 'within tolerance',
      ).toBeLessThanOrEqual(0);
    });
  }
});
